# Generated by Django 4.2.30 on 2026-08-31 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('importance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('event_date', models.DateField(db_index=True)),
                ('actual_value', models.CharField(blank=True, default='', max_length=100)),
                ('forecast_value', models.CharField(blank=True, default='', max_length=100)),
                ('previous_value', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(default='FRED', max_length=50)),
                ('source_url', models.URLField(blank=True, default='')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_economic_event',
                'ordering': ['-event_date', '-importance'],
            },
        ),
        migrations.CreateModel(
            name='MarketNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, default='')),
                ('source_name', models.CharField(blank=True, default='', max_length=200)),
                ('source_url', models.URLField(blank=True, default='')),
                ('related_symbols', models.JSONField(blank=True, default=list)),
                ('sentiment', models.CharField(blank=True, default='', help_text='positive/negative/neutral or empty if unknown', max_length=20)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_market_news',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, default='')),
                ('source_name', models.CharField(blank=True, default='', max_length=200)),
                ('source_url', models.URLField(blank=True, default='')),
                ('sentiment', models.CharField(blank=True, default='', max_length=20)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='assets.asset')),
            ],
            options={
                'db_table': 'news_asset_news',
                'ordering': ['-published_at'],
            },
        ),
    ]
