# Generated by Django 4.2.30 on 2026-09-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketnews',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
