# Generated by Django 4.2.30 on 2026-09-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_marketnews_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicevent',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
