# Generated by Django 4.2.30 on 2026-08-31 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Display symbol (e.g. EUR/USD, AAPL, BTC)', max_length=20, unique=True)),
                ('yfinance_symbol', models.CharField(help_text='yfinance ticker (e.g. EURUSD=X, AAPL, BTC-USD)', max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_class', models.CharField(choices=[('stock', 'Stock'), ('forex', 'Forex'), ('crypto', 'Crypto')], db_index=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delisted', models.BooleanField(default=False)),
                ('delisted_at', models.DateTimeField(blank=True, null=True)),
                ('delisted_reason', models.TextField(blank=True, default='')),
                ('last_price', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('last_change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets_asset',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='assets.asset')),
            ],
            options={
                'db_table': 'assets_price_snapshot',
                'ordering': ['-snapshot_date'],
                'unique_together': {('asset', 'snapshot_date')},
            },
        ),
    ]
