# Generated by Django 4.2.30 on 2026-09-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='breaking_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='daily_market_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='price_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='probability_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='product_updates',
            field=models.BooleanField(default=False),
        ),
    ]
