# Generated by Django 4.2.30 on 2026-09-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersettings_breaking_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
