# Generated by Django 4.2.30 on 2026-09-02 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('market_news', 'Market news')], default='market_news', max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, default='', max_length=200)),
                ('link_url', models.URLField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_appnotification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='appnotification',
            constraint=models.UniqueConstraint(fields=('user', 'source_ref'), name='uniq_user_source_ref'),
        ),
    ]
